### ISSUE TITLE
A service without a ready script which exits nonzero is considered up.

### ISSUE THREAD

**Issue by asottile** [Yelp/pgctl#127]
For example, a malformed haproxy configuration

**Comment by chriskuehl** [comment]
This is a little tricky: if the service exits immediately nonzero, then it will typically be down during the poll, and so you don't see this problem, and `pgctl start` eventually fails.

If instead it, for example, sleeps first, then it's easy to reproduce because the poll happens while it's "up":

```
#!/bin/bash -eu
sleep 1
exit 1
```

:\
